// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'button': string;
  'column': string;
  'container': string;
  'description': string;
  'label': string;
  'ms-Grid': string;
  'reactQueryExample': string;
  'row': string;
  'subTitle': string;
  'title': string;
}
const cssExports: CssExports;
export default cssExports;
