/** Declaration file generated by dts-gen */

export const id: string;

export function afterDatasetDraw(chart: any): void;

export function afterInit(chart: any): void;

export function afterUpdate(chart: any, options: any): void;

export function beforeDatasetDraw(chart: any, args: any): any;

export function beforeEvent(chart: any, event: any): any;

export function beforeInit(chart: any): void;

export function beforeUpdate(chart: any): any;

export function destroy(chart: any): void;

export namespace afterDatasetDraw {
    const prototype: {
    };

}

export namespace afterInit {
    const prototype: {
    };

}

export namespace afterUpdate {
    const prototype: {
    };

}

export namespace beforeDatasetDraw {
    const prototype: {
    };

}

export namespace beforeEvent {
    const prototype: {
    };

}

export namespace beforeInit {
    const prototype: {
    };

}

export namespace beforeUpdate {
    const prototype: {
    };

}

export namespace destroy {
    const prototype: {
    };

}

