// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8841dfc744bce6b2d3e075f7ace25c0c1e664c17/react-slick/index.d.ts
interface __config {
  className?: string
  adaptiveHeight?: boolean
  arrows?: boolean
  autoplay?: boolean
  autoplaySpeed?: number // integer
  centerMode?: boolean
  centerPadding?: string | any
  cssEase?: string | any
  dots?: boolean
  dotsClass?: string
  draggable?: boolean
  easing?: string
  fade?: boolean
  focusOnSelect?: boolean
  infinite?: boolean //   should the gallery wrap around it's contents
  initialSlide?: number // int
  lazyLoad?: boolean
  rtl?: boolean
  slide?: string
  slidesToShow?: number // int
  slidesToScroll?: number //  int
  speed?: number //int
  swipe?: boolean
  swipeToSlide?: boolean
  touchMove?: boolean
  touchThreshold?: number // int
  variableWidth?: boolean
  useCSS?: boolean
  vertical?: boolean
  afterChange?: (() => void)
  beforeChange?: (() => void)
  slickGoTo?: number // int
}

interface Slider extends __config {
  responsive?: { breakpoint: number; settings: __config}[]
}

declare module "react-slick" {
  var Slider: React.ClassicComponentClass<Slider>;
  export = Slider;
}
