name: Generate author avatars
description: Normalize author avatars + rewrite all-samples.json authors.pictureUrl (publish to Docs branch)

inputs:
  node-version:
    required: false
    default: "20"
  docs-path:
    required: false
    default: "Docs"
  all-samples-path:
    required: false
    default: ".metadata/all-samples.json"
  install-deps:
    required: false
    default: "true"

outputs:
  avatars_generated:
    description: Number of avatar files generated/updated
    value: ${{ steps.metrics.outputs.avatars_generated }}
  authors_updated:
    description: Number of author entries whose pictureUrl was set/rewritten
    value: ${{ steps.metrics.outputs.authors_updated }}
  avatars_skipped:
    description: Number skipped (missing/unsupported)
    value: ${{ steps.metrics.outputs.avatars_skipped }}
  avatars_deleted:
    description: Number of avatar images deleted as orphans
    value: ${{ steps.metrics.outputs.avatars_deleted }}

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install avatar deps
      if: ${{ inputs.install-deps == 'true' }}
      shell: bash
      run: |
        npm init -y >/dev/null 2>&1
        npm install sharp >/dev/null 2>&1

    - id: metrics
      name: Normalize author avatars + rewrite all-samples.json authors.pictureUrl (publish to Docs branch)
      shell: bash
      run: |
        node << 'EOF'
        const fs = require("fs");
        const path = require("path");
        const sharp = require("sharp");

        const docsPath = process.env.DOCS_PATH || "Docs";
        const allSamplesPath = path.resolve(process.env.ALL_SAMPLES_PATH || ".metadata/all-samples.json");

        const repo = process.env.GITHUB_REPOSITORY;
        const repoName = repo.split("/")[1];
        const pagesBase = `/${repoName}/`;
        const avatarUrlBase = `${pagesBase}images/avatars/`;

        const samples = JSON.parse(fs.readFileSync(allSamplesPath, "utf8"));

        const avatarsDir = path.resolve(docsPath, "docs/images/avatars");
        fs.mkdirSync(avatarsDir, { recursive: true });

        let avatarsGenerated = 0;
        let authorsUpdated = 0;
        let avatarsSkipped = 0;
        let avatarsDeleted = 0;

        // Track which files should exist after generation
        const expectedFiles = new Set([".gitkeep"]); // keep if you use one; safe even if it doesn't exist

        function safeFileName(name) {
          return String(name).replace(/[^a-zA-Z0-9._-]/g, "_");
        }

        function getAllAuthors(sample) {
          if (Array.isArray(sample.authors)) return sample.authors;
          if (sample.author) return [sample.author];
          return [];
        }

        // If you want remote avatar downloading, we can add it. For now: skip remote.
        async function normalizeAvatar(url) {
          if (!url || typeof url !== "string") {
            avatarsSkipped += 1;
            return null;
          }

          if (url.startsWith("http://") || url.startsWith("https://")) {
            avatarsSkipped += 1;
            return null;
          }

          const inputPath = path.resolve(url);
          if (!fs.existsSync(inputPath)) {
            avatarsSkipped += 1;
            return null;
          }

          const base = safeFileName(path.basename(inputPath, path.extname(inputPath)));
          const outFile = `${base}.webp`;
          const outPath = path.join(avatarsDir, outFile);

          expectedFiles.add(outFile);

          if (!fs.existsSync(outPath)) {
            try {
              await sharp(inputPath)
                .resize({ width: 160, height: 160, fit: "cover" })
                .webp({ quality: 82 })
                .toFile(outPath);
              avatarsGenerated += 1;
            } catch (e) {
              avatarsSkipped += 1;
              // If generation failed, don't treat output as expected
              expectedFiles.delete(outFile);
              return null;
            }
          }

          return outFile;
        }

        (async () => {
          for (const s of samples) {
            const authors = getAllAuthors(s);
            if (!authors.length) continue;

            for (const a of authors) {
              if (!a) continue;

              const current =
                a.pictureUrl ||
                a.avatarUrl ||
                a.image ||
                a.picture ||
                null;

              const outFile = await normalizeAvatar(current);
              if (!outFile) continue;

              a.pictureUrl = `${avatarUrlBase}${outFile}`;
              authorsUpdated += 1;
            }

            s.authors = authors;
          }

          fs.writeFileSync(allSamplesPath, JSON.stringify(samples, null, 2) + "\n");

          // Delete orphaned avatar images (anything not in expectedFiles)
          if (fs.existsSync(avatarsDir)) {
            for (const f of fs.readdirSync(avatarsDir)) {
              // Ignore directories + non-images if needed
              const full = path.join(avatarsDir, f);
              if (!fs.statSync(full).isFile()) continue;

              // If you have a manifest.json or other keepers, add them to expectedFiles
              if (!expectedFiles.has(f)) {
                fs.unlinkSync(full);
                avatarsDeleted += 1;
              }
            }
          }

          // Outputs
          const outPath = process.env.GITHUB_OUTPUT;
          fs.appendFileSync(outPath, `avatars_generated=${avatarsGenerated}\n`);
          fs.appendFileSync(outPath, `authors_updated=${authorsUpdated}\n`);
          fs.appendFileSync(outPath, `avatars_skipped=${avatarsSkipped}\n`);
          fs.appendFileSync(outPath, `avatars_deleted=${avatarsDeleted}\n`);

          // Step summary
          const summaryPath = process.env.GITHUB_STEP_SUMMARY;
          const lines = [];
          lines.push(`## Avatars`);
          lines.push(`- Avatars generated/updated: **${avatarsGenerated}**`);
          lines.push(`- Author entries updated: **${authorsUpdated}**`);
          lines.push(`- Skipped: **${avatarsSkipped}**`);
          lines.push(`- Deleted (orphans): **${avatarsDeleted}**`);
          fs.appendFileSync(summaryPath, lines.join("\n") + "\n");
        })().catch(err => {
          console.error(err);
          process.exit(1);
        });
        EOF
      env:
        DOCS_PATH: ${{ inputs.docs-path }}
        ALL_SAMPLES_PATH: ${{ inputs.all-samples-path }}
