// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'buttonsContainer': string;
  'form': string;
  'title': string;
}
const cssExports: CssExports;
export default cssExports;
