name: 'Tally Discussion Reactions'
description: 'Tallies reactions from GitHub discussions'

outputs:
  result:
    description: 'JSON string with reaction tallies'
    value: ${{ steps.tally.outputs.result }}

runs:
  using: "composite"
  steps:
    - name:  Tally reactions
      id: tally
      uses: actions/github-script@v7
      with:
        script: |
          async function fetchAllDiscussions(github, owner, repo, categoryName) {
            // First, get the category ID
            const categoriesQuery = `
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name:  $repo) {
                  discussionCategories(first: 100) {
                    nodes {
                      id
                      name
                    }
                  }
                }
              }
            `;
            
            const categoriesResult = await github.graphql(categoriesQuery, { owner, repo });
            const categories = categoriesResult.repository.discussionCategories.nodes;
            const likesCategory = categories.find(cat => cat.name === categoryName);
            
            if (!likesCategory) {
              throw new Error(`Category "${categoryName}" not found. Available: ${categories.map(c => c.name).join(', ')}`);
            }
            
            const categoryId = likesCategory.id;
            console.log(`Found category "${categoryName}" with ID: ${categoryId}`);
            
            const allDiscussions = [];
            let discussionCursor = null;
            let hasNextPage = true;
            
            while (hasNextPage) {
              const query = `
                query($owner: String!, $repo: String!, $categoryId:  ID!, $cursor: String) {
                  repository(owner: $owner, name: $repo) {
                    discussions(first: 100, after: $cursor, categoryId: $categoryId) {
                      nodes {
                        number
                        title
                        url
                        category {
                          name
                          id
                        }
                        reactions(first:  100) {
                          nodes {
                            content
                            user {
                              login
                            }
                          }
                          pageInfo {
                            hasNextPage
                            endCursor
                          }
                          totalCount
                        }
                      }
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                    }
                  }
                }
              `;
              
              const result = await github.graphql(query, {
                owner,
                repo,
                categoryId:  categoryId,
                cursor: discussionCursor
              });
              
              const discussions = result.repository.discussions.nodes;
              
              // For each discussion, paginate through ALL reactions if needed
              for (const discussion of discussions) {
                const allReactions = [...discussion.reactions.nodes];
                let reactionCursor = discussion.reactions.pageInfo.endCursor;
                let hasMoreReactions = discussion.reactions.pageInfo.hasNextPage;
                
                while (hasMoreReactions) {
                  const reactionQuery = `
                    query($owner: String!, $repo:  String!, $number: Int!, $cursor: String) {
                      repository(owner: $owner, name: $repo) {
                        discussion(number: $number) {
                          reactions(first: 100, after: $cursor) {
                            nodes {
                              content
                              user {
                                login
                              }
                            }
                            pageInfo {
                              hasNextPage
                              endCursor
                            }
                          }
                        }
                      }
                    }
                  `;
                  
                  const reactionResult = await github.graphql(reactionQuery, {
                    owner,
                    repo,
                    number: discussion.number,
                    cursor: reactionCursor
                  });
                  
                  allReactions.push(...reactionResult.repository.discussion.reactions.nodes);
                  hasMoreReactions = reactionResult.repository.discussion.reactions.pageInfo.hasNextPage;
                  reactionCursor = reactionResult.repository.discussion.reactions.pageInfo.endCursor;
                }
                
                // Replace with all reactions
                discussion.reactions.nodes = allReactions;
                discussion.reactions.totalCount = allReactions.length;
                
                allDiscussions.push(discussion);
              }
              
              hasNextPage = result.repository.discussions.pageInfo.hasNextPage;
              discussionCursor = result.repository.discussions.pageInfo.endCursor;
            }
            
            return allDiscussions;
          }

          // Main logic starts here
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const categoryName = "Likes";

          console.log(`Fetching all discussions in category "${categoryName}" and their reactions...`);
          const allDiscussions = await fetchAllDiscussions(github, owner, repo, categoryName);
          console.log(`Fetched ${allDiscussions.length} discussions from "${categoryName}" category`);

          // Define your pattern (optional - only if you want to filter by title too)
          const titlePattern = /^sample:/i;

          // Filter and tally reactions
          const tally = {};
          const allReactors = new Map();

          for (const discussion of allDiscussions) {
            // Optional: Check if discussion matches title pattern
            if (! titlePattern.test(discussion.title)) {
              continue;
            }
            
            const reactionsByType = {};
            const reactorsByType = {};
            const allDiscussionReactors = new Set();
            
            for (const reaction of discussion.reactions.nodes) {
              const reactionType = reaction.content;
              const userLogin = reaction.user.login;
              
              // Count reactions by type
              reactionsByType[reactionType] = (reactionsByType[reactionType] || 0) + 1;
              
              // Track reactors by reaction type (login only)
              if (!reactorsByType[reactionType]) {
                reactorsByType[reactionType] = [];
              }
              reactorsByType[reactionType].push(userLogin);
              
              // Track all unique reactors for this discussion
              allDiscussionReactors.add(userLogin);
              
              // Track globally across all matching discussions
              if (!allReactors.has(userLogin)) {
                allReactors.set(userLogin, {
                  login: userLogin,
                  reactedToCount: 0,
                  discussions: []
                });
              }
              
              const reactor = allReactors.get(userLogin);
              if (!reactor.discussions.includes(discussion.number)) {
                reactor.discussions.push(discussion.number);
                reactor.reactedToCount++;
              }
            }
            
            if (discussion.reactions.totalCount > 0) {
              tally[discussion.title] = {
                url: discussion.url,
                totalReactions: discussion.reactions.totalCount,
                reactionCounts: reactionsByType,
                allReactors: Array.from(allDiscussionReactors)
              };
            }
          }

          const result = {
            generatedAt: new Date().toISOString(),
            discussions: tally
          };

          console.log(`Matched ${Object.keys(tally).length} discussions`);
          console.log(`Found ${reactorSummary.length} unique reactors`);
          console.log('Reaction Tally:', JSON.stringify(result, null, 2));

          core.setOutput('result', JSON.stringify(result));
          
          return result;