// Generated by typings
declare module "redux-promise-middleware" {
    function promiseMiddleware(config?: { promiseTypeSuffixes: string[] }): Redux.Middleware;

    export default promiseMiddleware;
}
