// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'cascadingManagedMetadata': string;
  'column': string;
  'container': string;
  'description': string;
  'label': string;
  'ms-Grid': string;
  'row': string;
  'subTitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
