// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carouselDot': string;
  'carouselDotsContainer': string;
  'centerPadding': string;
  'filmStrip': string;
  'filmstripLayout': string;
  'indexButton': string;
  'indexButtonContainer': string;
  'leftPositioned': string;
  'rightPositioned': string;
  'sliderButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
